In [1]:
import sys 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
sys.path.append('/home/rosselli/fisher_howlett/')
from fisher import fisher_class as fc
from fisher import utils as ut

#parameter file with the info for the forecast, check params.yml for description
param_file = '../example_files/params.yml'



In [2]:
#initialize the class and run the forecast in redshift bins as defined in the param_file
# for the moment verbose = False in param_file put True if you want the code to print a lot of stuff
c = fc.Fisher(param_file)
c.compute_fisher_zbin()


Evaluating the Fisher Matrix for 10 bins between [z_min = 0.0, z_max = 0.5]


  0%|          | 0/10 [00:00<?, ?it/s]

Evaluating the Fisher Matrix for [k_min = 0.021230715149842275, k_max = 0.2] and [z_min = 0.0, z_max = 0.05]


 10%|█         | 1/10 [00:28<04:16, 28.52s/it]

Fisher Matrix 

[ 7930.42879708 -8059.02151607    47.79653836] 

[-8059.02151607  8271.44517742   -53.57317973] 

[ 47.79653836 -53.57317973   0.68860132] 


Effective redshift z_eff = 0.03739405946602345
beta(z_eff) 	 percentage error(z_eff)
0.400979 	 53.557477
fsigma8(z_eff) 	 percentage error(z_eff)
0.438276 	 51.951980
sigma_g 	 percentage error
4.240000 	 76.718155
sigma_u 	 percentage error
13.000000 	 25.021921
Evaluating the Fisher Matrix for [k_min = 0.010745578885933008, k_max = 0.2] and [z_min = 0.05, z_max = 0.1]


 20%|██        | 2/10 [00:52<03:27, 25.97s/it]

Fisher Matrix 

[ 50650.50526006 -51564.25267041    311.33293385] 

[-51564.25267041  53037.27432846   -350.27159786] 

[ 311.33293385 -350.27159786    4.59540929] 


Effective redshift z_eff = 0.08014207292432711
beta(z_eff) 	 percentage error(z_eff)
0.409375 	 20.322448
fsigma8(z_eff) 	 percentage error(z_eff)
0.447453 	 19.696511
sigma_g 	 percentage error
4.240000 	 29.571836
sigma_u 	 percentage error
13.000000 	 9.644968
Evaluating the Fisher Matrix for [k_min = 0.007253768252586117, k_max = 0.2] and [z_min = 0.1, z_max = 0.15]


 30%|███       | 3/10 [01:17<02:56, 25.28s/it]

Fisher Matrix 

[ 124368.12259982 -126833.82585477     779.17608947] 

[-126833.82585477  130730.72776046    -879.77573709] 

[ 779.17608947 -879.77573709   11.76206225] 


Effective redshift z_eff = 0.12804335943924916
beta(z_eff) 	 percentage error(z_eff)
0.417266 	 12.491536
fsigma8(z_eff) 	 percentage error(z_eff)
0.456078 	 12.097712
sigma_g 	 percentage error
4.240000 	 18.444678
sigma_u 	 percentage error
13.000000 	 6.015803
Evaluating the Fisher Matrix for [k_min = 0.005510166460968095, k_max = 0.2] and [z_min = 0.15, z_max = 0.2]


 40%|████      | 4/10 [01:42<02:32, 25.40s/it]

Fisher Matrix 

[ 220933.58181865 -225635.13786008    1405.92565056] 

[-225635.13786008  232965.79355527   -1592.11190612] 

[ 1405.92565056 -1592.11190612    21.61498824] 


Effective redshift z_eff = 0.17710480918707644
beta(z_eff) 	 percentage error(z_eff)
0.423773 	 9.095274
fsigma8(z_eff) 	 percentage error(z_eff)
0.463191 	 8.803297
sigma_g 	 percentage error
4.240000 	 13.588121
sigma_u 	 percentage error
13.000000 	 4.431818
Evaluating the Fisher Matrix for [k_min = 0.004465747589198563, k_max = 0.2] and [z_min = 0.2, z_max = 0.25]


 50%|█████     | 5/10 [02:08<02:08, 25.63s/it]

Fisher Matrix 

[ 333282.87785626 -340773.85418778    2146.45594679] 

[-340773.85418778  352337.55810646   -2436.38924338] 

[ 2146.45594679 -2436.38924338    33.46595792] 


Effective redshift z_eff = 0.22658572103853303
beta(z_eff) 	 percentage error(z_eff)
0.428831 	 7.230055
fsigma8(z_eff) 	 percentage error(z_eff)
0.468719 	 6.994223
sigma_g 	 percentage error
4.240000 	 10.901027
sigma_u 	 percentage error
13.000000 	 3.555412
Evaluating the Fisher Matrix for [k_min = 0.0037708355696927745, k_max = 0.2] and [z_min = 0.25, z_max = 0.3]


 60%|██████    | 6/10 [02:34<01:42, 25.74s/it]

Fisher Matrix 

[ 454830.03864814 -465506.33427823    2954.6871875 ] 

[-465506.33427823  481856.2353204    -3359.83669001] 

[ 2954.6871875  -3359.83669001    46.53097383] 


Effective redshift z_eff = 0.27623110491498015
beta(z_eff) 	 percentage error(z_eff)
0.432503 	 6.072117
fsigma8(z_eff) 	 percentage error(z_eff)
0.472733 	 5.870963
sigma_g 	 percentage error
4.240000 	 9.219495
sigma_u 	 percentage error
13.000000 	 3.006974
Evaluating the Fisher Matrix for [k_min = 0.003275569595692925, k_max = 0.2] and [z_min = 0.3, z_max = 0.35]


 70%|███████   | 7/10 [03:00<01:16, 25.66s/it]

Fisher Matrix 

[ 583376.30083199 -597505.6598373     3811.14193248] 

[-597505.6598373   619018.05508991   -4339.17324843] 

[ 3811.14193248 -4339.17324843    60.40722417] 


Effective redshift z_eff = 0.3259898432942916
beta(z_eff) 	 percentage error(z_eff)
0.434901 	 5.288473
fsigma8(z_eff) 	 percentage error(z_eff)
0.475354 	 5.110993
sigma_g 	 percentage error
4.240000 	 8.068576
sigma_u 	 percentage error
13.000000 	 2.631597
Evaluating the Fisher Matrix for [k_min = 0.002905020325657503, k_max = 0.2] and [z_min = 0.35, z_max = 0.4]


 80%|████████  | 8/10 [03:27<00:52, 26.20s/it]

Fisher Matrix 

[ 706498.00958265 -724114.4642104     4628.66056318] 

[-724114.4642104   750772.1995984    -5274.83140335] 

[ 4628.66056318 -5274.83140335    73.59212264] 


Effective redshift z_eff = 0.3757807775164316
beta(z_eff) 	 percentage error(z_eff)
0.436141 	 4.749217
fsigma8(z_eff) 	 percentage error(z_eff)
0.476710 	 4.587124
sigma_g 	 percentage error
4.240000 	 7.271925
sigma_u 	 percentage error
13.000000 	 2.371766
Evaluating the Fisher Matrix for [k_min = 0.0026175618235239045, k_max = 0.2] and [z_min = 0.4, z_max = 0.45]


 90%|█████████ | 9/10 [03:53<00:26, 26.13s/it]

Fisher Matrix 

[ 792377.2240579  -813019.42612264    5191.09060865] 

[-813019.42612264  843934.30671913   -5921.60213238] 

[ 5191.09060865 -5921.60213238    82.50154236] 


Effective redshift z_eff = 0.4255013231154968
beta(z_eff) 	 percentage error(z_eff)
0.436346 	 4.411282
fsigma8(z_eff) 	 percentage error(z_eff)
0.476934 	 4.255539
sigma_g 	 percentage error
4.240000 	 6.782232
sigma_u 	 percentage error
13.000000 	 2.212051
Evaluating the Fisher Matrix for [k_min = 0.002388220227094578, k_max = 0.2] and [z_min = 0.45, z_max = 0.5]


100%|██████████| 10/10 [04:21<00:00, 26.14s/it]

Fisher Matrix 

[ 802340.0326817  -824765.47266865    5234.26165621] 

[-824765.47266865  857795.46490171   -5979.08038278] 

[ 5234.26165621 -5979.08038278    82.80746709] 


Effective redshift z_eff = 0.47520343193815007
beta(z_eff) 	 percentage error(z_eff)
0.435638 	 4.266463
fsigma8(z_eff) 	 percentage error(z_eff)
0.476160 	 4.106098
sigma_g 	 percentage error
4.240000 	 6.603047
sigma_u 	 percentage error
13.000000 	 2.153609
Evaluation of the Fisher Matrix for 10 bins between [z_min = 0.0, z_max = 0.5] is COMPLETE!!


In [3]:
#all the result of the forecast are save in a dictionary
c.data

{0: {'zbin': [0.0, 0.05],
  'zeff': 0.03739405946602345,
  'beta_eff': 0.4009788331340625,
  'beta_eff_err': 0.21475414677859234,
  'fs8_eff': 0.43827639306159527,
  'fs8_eff_err': 0.22769326315165267,
  'sigma_g': 4.24,
  'sigma_g_err': 3.2528497622544164,
  'sigma_u': 13.0,
  'sigma_u_err': 3.2528497622544164},
 1: {'zbin': [0.05, 0.1],
  'zeff': 0.08014207292432711,
  'beta_eff': 0.40937452471429003,
  'beta_eff_err': 0.08319492377517786,
  'fs8_eff': 0.44745302065133513,
  'fs8_eff_err': 0.08813263457285817,
  'sigma_g': 4.24,
  'sigma_g_err': 1.2538458673826347,
  'sigma_u': 13.0,
  'sigma_u_err': 1.2538458673826347},
 2: {'zbin': [0.1, 0.15],
  'zeff': 0.12804335943924916,
  'beta_eff': 0.41726555934942905,
  'beta_eff_err': 0.05212287761686469,
  'fs8_eff': 0.45607804998363555,
  'fs8_eff_err': 0.055175007661228,
  'sigma_g': 4.24,
  'sigma_g_err': 0.7820543468519875,
  'sigma_u': 13.0,
  'sigma_u_err': 0.7820543468519875},
 3: {'zbin': [0.15, 0.2],
  'zeff': 0.17710480918707644

In [4]:
#here are saved all the Fisher matrix for each redshift bin
c.Fisher_zbin

array([[[ 7.93042880e+03, -8.05902152e+03,  4.77965384e+01],
        [-8.05902152e+03,  8.27144518e+03, -5.35731797e+01],
        [ 4.77965384e+01, -5.35731797e+01,  6.88601323e-01]],

       [[ 5.06505053e+04, -5.15642527e+04,  3.11332934e+02],
        [-5.15642527e+04,  5.30372743e+04, -3.50271598e+02],
        [ 3.11332934e+02, -3.50271598e+02,  4.59540929e+00]],

       [[ 1.24368123e+05, -1.26833826e+05,  7.79176089e+02],
        [-1.26833826e+05,  1.30730728e+05, -8.79775737e+02],
        [ 7.79176089e+02, -8.79775737e+02,  1.17620623e+01]],

       [[ 2.20933582e+05, -2.25635138e+05,  1.40592565e+03],
        [-2.25635138e+05,  2.32965794e+05, -1.59211191e+03],
        [ 1.40592565e+03, -1.59211191e+03,  2.16149882e+01]],

       [[ 3.33282878e+05, -3.40773854e+05,  2.14645595e+03],
        [-3.40773854e+05,  3.52337558e+05, -2.43638924e+03],
        [ 2.14645595e+03, -2.43638924e+03,  3.34659579e+01]],

       [[ 4.54830039e+05, -4.65506334e+05,  2.95468719e+03],
        [-4.65

In [5]:
#compute Fisher forecast for the whole redshift range
c.compute_fisher_tot()

#result save in c.data_tot
#Fisher matrix save in c.Fisher_tot

Evaluating the Fisher Matrix between [z_min = 0.0, z_max = 0.5]
Fisher Matrix 

[ 4076587.12213424 -4177777.44920632    26510.52910706] 

[-4177777.44920632  4330719.06055762   -30186.64552114] 

[ 26510.52910706 -30186.64552114    417.96634912] 


Effective redshift z_eff = 0.3585957498352305
beta(z_eff) 	 percentage error(z_eff)
0.435837 	 1.972704
fsigma8(z_eff) 	 percentage error(z_eff)
0.476377 	 1.904674
sigma_g 	 percentage error
4.240000 	 3.030252
sigma_u 	 percentage error
13.000000 	 0.988328
